### ISSUE TITLE
pre-commit pylint hook doesn't use configuration file

### ISSUE THREAD

**Issue by jovans-getpassport** [jenstroeger/python-package-template#113]
The pre-commit-config file doesn't specify the configuration file(pylintrc) for pylint, so the pylint hook is running with its default settings.
This introduces a discrepancy between running pylint from pre-commit and github workflows.

The pre-commit-config for the pylint hook should be defined as:
```
- repo: local
  hooks:
  - id: pylint
    name: Check lint
    entry: pylint
    language: python
    files: ^src/package/|^tests/|setup.py
    args: [--rcfile=pylintrc]
```
