### ISSUE TITLE
Unnecessary env in Action steps

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#238]
I think these environment variables:

https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/.github/workflows/build.yaml#L35-L36

https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/.github/workflows/codeql-analysis.yaml#L51-L52

aren’t necessary because `make setup` assumes a venv. The `PYTHON` environment variable is used only by the `make venv` goal to pick the Python for the virtual environment:

https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/Makefile#L29-L42

**Comment by jenstroeger** [comment]
Also, I think if we replace this

https://github.com/jenstroeger/python-package-template/blob/66347c69af6dd9c30b2b85ebe022d2844573faee/.github/workflows/build.yaml#L37-L43

with
```yaml
    # We don't need to check and test the package separately
    # because `make dist` runs those targets first and only
    # builds the package if they succeed.
    - name: Build the package artifacts and documentation
      run: make dist docs
```
then the tests will run only once because `make` resolves the common `check test` dependency of the `dist` and `doc` goals.
