### ISSUE TITLE
Auto-merge Dependabot PRs on approval.

### ISSUE THREAD

**Issue by jenstroeger** [jenstroeger/python-package-template#373]
I think it would make our lives a little easier to automatically merge Dependabot PRs upon approval.

Unfortunately, [Dependabot’s configuration](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) doesn’t support such a feature so we may want to consider the [`pull_request_review` event with `submitted` type](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved). There’s some more useful information in the Github’s [Enable auto-merge on a pull request](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request) as well.

**Comment by jenstroeger** [comment]
This one seems to work in a private test repository:
```yaml

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write

jobs:
  approved:
    if: ${{ github.event.review.state == 'approved' && github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Merge Dependabot PR
      run: gh pr comment --body "@dependabot squash and merge" "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN: ${{ secrets.DEPENDABOT_AUTOMERGE }}
```
The `DEPENDABOT_AUTOMERGE` secret needs to be created by a user with push permissions and it needs `repo` permissions. @behnazh I am not sure whether the `permissions:` are too broad, I’ll keep testing.

Commenting on the PR seems to work and sometimes not, so an alternative would be
```yaml
run: gh pr merge --delete-branch --squash "$PR_URL"
```

Also, it seems that the Dependabot PR needs to be based on a branch which already has this workflow available 🤔
